include: "rules/common.smk"

print("snakefile")
rule all:
    input:
        primers = get_all_primers()


include: "rules/sequence_processing.smk"
include: "rules/primer_search.smk"
include: "rules/primer_selection.smk"
