# Path to assembly units sheet
assemblies_units_path: config/assembly_units.txt
# Path to target variants sheet
target_variants_path: config/target_variants.txt
# Window length (in pb) to define the roi
window_length: 50
# Maxmimun distance in pb to search common primers
max_dist: 20

# Primer3 preset settings for primer discriminative
conf_primer_discriminative: data/primer_discriminative.txt

# Primer3 preset settings for alternative primer check
conf_primercheck: data/primer_check.txt
